### ISSUE TITLE
Move this repo to ipfs-shipyard and make it public?

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/pm-ipfs-gui#19]
Hi all! I'm thinking that now that a team is assembled and we have identified goals, it is a good time to move this repo into the open so that others can subscribe to it. What do you think?

**Comment by lidel** [comment]
@diasdavid seems to be done – can you close this one?
(I would do that, but I don't see the button, probably lacking permissions still)

**Comment by diasdavid** [comment]
@lidel fixed the permissions issue :)
