### ISSUE TITLE
Merge the IPFS GUI Weekly Sync up with the IPFS in Web Browsers Working Group Weekly

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/pm-ipfs-gui#26]
Following up on [@hacdias' question](https://github.com/ipfs/in-web-browsers/issues/74) and the IPFS in Web Browsers Working Group formation, [owning this project](https://github.com/ipfs/in-web-browsers/pull/75), I propose that we only have one Weekly sync up for the Working Group and respective projects rather than multiple independent sync-ups.

The team is small now (~6 people) and a one hour long call should e enough. What do you think?

**Comment by hacdias** [comment]
I agree!

**Comment by hacdias** [comment]
@diasdavid and today there won't be the sync up?

**Comment by diasdavid** [comment]
Got thumbs up from everyone in this thread. Let's agree on a new weekly sync time through https://github.com/ipfs/in-web-browsers/issues/74
