### ISSUE TITLE
please grant Zeplin access to @cvan

### ISSUE THREAD

**Issue by cvan** [ipfs-shipyard/pm-ipfs-gui#32]
per [@lidel's comment](https://github.com/ipfs-shipyard/ipfs-companion/issues/273#issuecomment-371257197), would I be able to get access to the [Zeplin project](https://app.zeplin.io/project/5a32d45d1a17248135241058)? (my Zeplin account is hearcomestreble` `gmail.)

thank you in advance for the help!

**Comment by lidel** [comment]
Done! 

Make sure to catch up with ongoing discussion in https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/12 about IPFS Desktop wireframe (1st iteration).
