### ISSUE TITLE
Design: Project Roadmap 

### ISSUE THREAD

**Issue by akrych** [ipfs-shipyard/pm-ipfs-gui#46]
Project roadmap for our IPFS In Web Browsers Working Group: 

<img width="842" alt="apps_roadmap" src="https://user-images.githubusercontent.com/22168118/37776081-d53429c6-2de4-11e8-83e5-be06e267b839.png">

**Comment by hacdias** [comment]
Go ahead @lidel!

**Comment by hacdias** [comment]
@lidel I went one step ahead and created a PR adding this to the README 😄 (#47)

**Comment by lidel** [comment]
Thanks @hacdias! 
Let's keep it open for now, I plan to add some context to README in following days in new PR :)

**Comment by lidel** [comment]
Done in  https://github.com/ipfs-shipyard/pm-ipfs-gui/pull/48#event-1545163604
