### ISSUE TITLE
Design: WebUI

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/pm-ipfs-gui#49]
As per our roadmap (#47), the next step to take is to create the wireframes for WebUI and then build it and make it awesome. So, I decided to open this issue to list the current features of WebUI, some suggestions and inspirational dashboards.

## Current Features

- Node informations such as:
	- ID
	- Public Key
	- Addresses
	- Location
- Peers:
	- Number os peers
	- Information about peers
	- A globe showing their location (**this globe consumes a lot of GPU and makes the page very slow on not so fast machines**).
- A file browser to add, remove, rename and manage MFS files.
- Preview files (music, video, images and PDFs).
- Page to edit the node settings.
- Object explorer (see #11).

There is also a logs page, which is not directly accessible through the sidebar, but you can to its URL (`/logs`). It's a bit buggy and can even block the page due to the huge amount of requests it makes.

## Suggested features

It's true that WebUI has some interesting features, but it could be a lot better. Let's see some things I'd like to see in WebUI:

- A new name. I know this is not a feature, but `WebUI` is a weird name to call to a Dashboard like this. Please see https://github.com/ipfs-shipyard/ipfs-webui/issues/612.
- A page to see statistics and beautiful graphs showing the change on Upload and Download speeds and the storage and some stuff like that.
	- We could store this data on `localStorage` so every time the user loaded the page, we would have something to start the graphics with.
- A way better file manager where we can move, download and copy files with better previews.
- The brand new [IPLD Explorer](./11).

**Comment by hacdias** [comment]
![image](https://user-images.githubusercontent.com/5447088/38019422-69e5107e-326f-11e8-8b50-b2816c7c21bc.png)

I like Bitbucket's colors and sidebar.

**Edit:** I'll try to add more examples soon.

**Comment by alanshaw** [comment]
@hacdias I think @olizilla has categorically covered the existing features in [these issues](https://github.com/ipfs-shipyard/pm-ipfs-gui/issues?q=is%3Aissue+is%3Aopen+label%3A%22existing+feature%22) as places for us to discuss. It would be good not to fragment the discussion.

For suggested features:

* New name - yes, I think we're all behind this
* Stats page - yes, perhaps a new issue with the feature request label? [I suggested something similar this morning](https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/33#issuecomment-376827954)
* File manager - your thoughts [should go here](https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/9)
* IPLD explorer - you linked to it!

I think @akrych would like your good application design examples [over here](https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/44)

**Comment by hacdias** [comment]
@alanshaw yeah, I agree and it's true that we have an issue for each separate feature, but we also need some inspiration on how to integrate everything (sidebar, menus, etc), in my opinion. That's why I created this issue.

**Comment by hacdias** [comment]
But if you all agree, @alanshaw @akrych @olizilla @lidel, I can close this one and move that suggestion to File Manager's issue.
