### ISSUE TITLE
Get Agatha familiar with WebUI, Station and IPFS Companion

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/pm-ipfs-gui#8]
Let's get Agatha using all of the tech we create :) 

Let's also use this as an experiment to get feedback from a user trying them for the first time. For this I ask:

- @lidel can you guide Agatha on installing ipfs-companion. Perhaps share links first and then if there are questions, set a quick call to answer them?
- @hacdias can you do the same for webui and station?
- @akrych can you write notes from your experience as a user? A UX review in depth.

**Comment by hacdias** [comment]
@akrych can we close this one? 😄 I think that at this stage, any doubt you have you will just ask us and not use this issue.

**Comment by akrych** [comment]
Sure :))))
